name        : polkit-gnome
version     : 0.105
release     : 7
source      :
    - http://ftp.gnome.org/pub/gnome/sources/polkit-gnome/0.105/polkit-gnome-0.105.tar.xz : 1784494963b8bf9a00eedc6cd3a2868fb123b8a5e516e66c5eda48df17ab9369
homepage    : http://www.gnome.org
license     :
    - GPLv3+
summary     : GNOME Polkit Authentication Agent
builddeps   :
    - pkgconfig(gtk+-3.0)
description : |
    The Polkit GNOME package provides an Authentication Agent for Polkit that integrates well with the GNOME Desktop environment.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    
    # Desktop file
    install -m 00644 -D $pkgfiles/polkit-gnome-authentication-agent-1.desktop $installdir/usr/share/xdg/autostart/polkit-gnome-authentication-agent-1.desktop
