name       : polkit-gnome
version    : '0.105'
release    : 15
source     :
    - https://download.gnome.org/sources/polkit-gnome/0.105/polkit-gnome-0.105.tar.xz : 1784494963b8bf9a00eedc6cd3a2868fb123b8a5e516e66c5eda48df17ab9369
homepage   : http://www.gnome.org
license    : GPL-3.0-or-later
component  : desktop.gnome.core
summary    : GNOME Polkit Authentication Agent
description: |
    The Polkit GNOME package provides an Authentication Agent for Polkit that integrates well with the GNOME Desktop environment.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
